# Form implementation generated from reading ui file 'testando.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Canvas(FigureCanvas):
    def __init__(self,parent,catupiry, cheeder, sem_borda, vulcao):
        fig, self.ax = plt.subplots(figsize=(1,52))
        fig.patch.set_alpha(0.1)

        super().__init__(fig)
        
        self.bordas = ['Catupity', 'Cheeder', 'Sem borda', 'Vulcão']
        self.valores = [catupiry, cheeder, sem_borda, vulcao]
        self.colors = ['#20B2AA', '#66CDAA', '#32CD32', '#DAA520']
        self.ax.legend(self.bordas)
        self.ax.pie(self.valores, labels=self.bordas, colors= self.colors)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{ background-color: rgb(0, 0, 0);}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")


        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgba(0, 0, 255,25);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)

        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setStyleSheet("background-color: rgb(21, 185, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        spacerItem = QtWidgets.QSpacerItem(20, 290, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)

        self.canvas = Canvas(self,15,15,15,30)
        self.verticalLayout_2.addWidget(self.canvas)

        #self.canvas = FigureCanvas(plt.Figure(figsize=(1,50)))
        #self.verticalLayout_2.addWidget(self.canvas)
        #self.insert_plot()

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #self.pushButton.clicked.connect(self.clic)

    """def clic(self):
        self.plot.clear()
        self.bordas = ['testeeeeeeeee', 'Cheeder', 'Sem borda', 'Vulcão']
        self.catupiry = 10
        self.valores = [self.catupiry, 20, 10, 5]
        self.plot.pie(self.valores, labels=self.bordas)
        self.canvas.draw()

    def insert_plot(self):
        self.plot = self.canvas.figure.subplots()
        self.bordas = ['Catupity', 'Cheeder', 'Sem borda', 'Vulcão']
        self.catupiry = 50
        self.valores = [self.catupiry, 20, 10, 5]
        self.plot.pie(self.valores, labels=self.bordas)
    """


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SAlveee sd a"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
