# Form implementation generated from reading ui file 'pizzaria.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(879, 744)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Palace Script MT")
        font.setPointSize(48)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(43, 180, 211)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 361, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(56, 177, 241)")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(50, 190, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 230, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 270, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 340, 321, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(56, 177, 241)")
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(50, 400, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 440, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 480, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(50, 520, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_final = QtWidgets.QLabel(Form)
        self.label_final.setGeometry(QtCore.QRect(170, 590, 581, 101))
        self.label_final.setText("")
        self.label_final.setObjectName("label_final")
        self.pushButton = QtWidgets.QPushButton(Form, clicked= lambda: self.btn_clicked())
        self.pushButton.setGeometry(QtCore.QRect(30, 590, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.radioButton.toggled.connect(self.radio_selected)
        self.radioButton_2.toggled.connect(self.radio_selected)
        self.radioButton_3.toggled.connect(self.radio_selected)
        self.checkBox.setChecked(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def radio_selected(self):
        self.radio=""
        if self.radioButton.isChecked():
            self.radio = self.radioButton.text()
        if self.radioButton_2.isChecked():
            self.radio = self.radioButton_2.text()
        if self.radioButton_3.isChecked():
            self.radio = self.radioButton_3.text()
    
    def btn_clicked(self):
        check1 = ""
        check2 = ""
        check3 = ""
        check4 = ""
        if self.checkBox.isChecked():
            check1=self.checkBox.text()
        if self.checkBox_2.isChecked():
            check2=self.checkBox_2.text()
        if self.checkBox_3.isChecked():
            check3=self.checkBox_3.text()
        if self.checkBox_4.isChecked():
            check4=self.checkBox_4.text()
        self.label_final.setText(f'Pizza sabor: {self.radio}, adicionais: {check1 + " "+ check2+" "+check3+" "+check4}')


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pizzaria Apollo Tech"))
        self.label_2.setText(_translate("Form", "Escolha o sabor da Pizza"))
        self.radioButton.setText(_translate("Form", "Mussarela"))
        self.radioButton_2.setText(_translate("Form", "Calabresa"))
        self.radioButton_3.setText(_translate("Form", "Frango"))
        self.label_3.setText(_translate("Form", "Escolha os adicionais"))
        self.checkBox.setText(_translate("Form", "Azeitona"))
        self.checkBox_2.setText(_translate("Form", "Bacon"))
        self.checkBox_3.setText(_translate("Form", "Palmito"))
        self.checkBox_4.setText(_translate("Form", "Milho"))
        self.pushButton.setText(_translate("Form", "Salvar e Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
