# Form implementation generated from reading ui file 'comboBoxQt.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(472, 402)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_pizza = QtWidgets.QComboBox(Form)
        self.comboBox_pizza.setGeometry(QtCore.QRect(310, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_pizza.setFont(font)
        self.comboBox_pizza.setObjectName("comboBox_pizza")
        self.comboBox_pizza.addItem("")
        self.comboBox_pizza.addItem("")
        self.comboBox_pizza.addItem("")
        self.comboBox_pizza.addItem("")
        self.comboBox_pizza.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_borda = QtWidgets.QComboBox(Form)
        self.comboBox_borda.setGeometry(QtCore.QRect(310, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_borda.setFont(font)
        self.comboBox_borda.setObjectName("comboBox_borda")
        self.comboBox_borda.addItem("")
        self.comboBox_borda.addItem("")
        self.comboBox_borda.addItem("")
        self.comboBox_borda.addItem("")
        self.label_final = QtWidgets.QLabel(Form)
        self.label_final.setGeometry(QtCore.QRect(60, 210, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(16)
        self.label_final.setFont(font)
        self.label_final.setText("")
        self.label_final.setObjectName("label_final")
        self.pushButton = QtWidgets.QPushButton(Form, clicked= self.btn_clicked)
        self.pushButton.setGeometry(QtCore.QRect(180, 280, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def btn_clicked(self):
        self.label_final.setText(f'Pizza de:{self.comboBox_pizza.currentText()}, borda de:{self.comboBox_borda.currentText()}.')


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Escolha o sabor da sua pizza:"))
        self.comboBox_pizza.setItemText(0, _translate("Form", "Sabores"))
        self.comboBox_pizza.setItemText(1, _translate("Form", "Mussarela"))
        self.comboBox_pizza.setItemText(2, _translate("Form", "Calabresa"))
        self.comboBox_pizza.setItemText(3, _translate("Form", "Atum"))
        self.comboBox_pizza.setItemText(4, _translate("Form", "Chocolate"))
        self.label_2.setText(_translate("Form", "Escolha sua borda:"))
        self.comboBox_borda.setItemText(0, _translate("Form", "Sem borda"))
        self.comboBox_borda.setItemText(1, _translate("Form", "Cheeder"))
        self.comboBox_borda.setItemText(2, _translate("Form", "Catupity"))
        self.comboBox_borda.setItemText(3, _translate("Form", "Chocolate"))
        self.pushButton.setText(_translate("Form", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
